Create stock model and its tests
Rubncal04/ManageStore pull request #6
Opened 2022-10-07 01:42 UTC by Rubncal04

Create the stock model and its tests when we create the stocks for products

2022-10-07 21:08 UTC, gabo-cs requested changes
Another question: Are products going to have multiple stocks? I don't see the `has_one`/`has_many` line change in the `Product` model. Can you give me an example of how that relationship going to work in your business logic?

2022-10-07 21:08 UTC, gabo-cs commented on spec/models/stock_spec.rb
> +    expect { stock.save!(validate: false) }.to raise_error ActiveRecord::NotNullViolation
Two questions here:
1) Why are you doing `validate: false`? What validations you want to skip?
2) You're validating that a stock shouldn't be saved without a product, and you're asserting against `ActiveRecord::NotNullViolation`. Shouldn't you be asserting against `ActiveRecord::RecordInvalid` instead. 

Doing `stock.save!` without a product should give you:
```
TRANSACTION (0.3ms)  ROLLBACK
ActiveRecord::RecordInvalid: Validation failed: Product must exist
```

2022-10-07 21:08 UTC, gabo-cs commented on spec/models/stock_spec.rb
> +  it "is valid with differents product id" do
```suggestion
  it "is valid with different product IDs" do
```

2022-10-07 21:08 UTC, gabo-cs commented on spec/models/stock_spec.rb
> +  it "is not valid with product id equals" do
```suggestion
  it "is not valid with product equal IDs" do
```

2022-10-08 16:49 UTC, Rubncal04 commented on spec/models/stock_spec.rb
> +    expect { stock.save!(validate: false) }.to raise_error ActiveRecord::NotNullViolation
No, the products are going to have one stock and that stock can be changed

2022-10-08 16:51 UTC, Rubncal04 commented on spec/models/stock_spec.rb
> +    expect { stock.save!(validate: false) }.to raise_error ActiveRecord::NotNullViolation
respect of your questions, the idea is validate that `product_id` exists and it cannot be created without it

2022-10-11 03:58 UTC, Rubncal04 commented
Implement another fix

2022-10-11 03:58 UTC, closed without merging